# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/distroless/static-debian12:nonroot@sha256:1b7b9f0f0e0a1d2155f531db587cc48ec26aaf97ab64364225f5bf18a054e66a

ARG BINARY_ARCH
USER nonroot
EXPOSE 8443
COPY --chown=root:root --chmod=0755 target/dist/dps-tls-proxy_linux_${BINARY_ARCH}/dps-tls-proxy /dps-tls-proxy
ENTRYPOINT ["/dps-tls-proxy"]
