**
!target/
!target/dist/
!target/dist/dps-bmc-simulator-config.yaml
!target/dist/dps-bmc-simulator-mockups/
!target/dist/dps-bmc-simulator-mockups/**
!target/dist/dps-bmc-simulator_linux_*/
!target/dist/dps-bmc-simulator_linux_*/dps-bmc-simulator
