// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpxPartitionCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpxPartitionCreateRequest{}

// SpxPartitionCreateRequest Request data to create an SPX Partition
type SpxPartitionCreateRequest struct {
	// Name of the SPX Partition
	Name string `json:"name"`
	// Optional description of the SPX Partition
	Description NullableString `json:"description,omitempty"`
	// ID of the Site where the SPX Partition is created
	SiteId string `json:"siteId"`
	// Exact VNI requested from Core. Omit or set to null to request allocation from the configured Core pool
	Vni NullableUint32 `json:"vni,omitempty"`
	// Optional user-defined key-value labels
	Labels map[string]string `json:"labels,omitempty"`
}

type _SpxPartitionCreateRequest SpxPartitionCreateRequest

// NewSpxPartitionCreateRequest instantiates a new SpxPartitionCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpxPartitionCreateRequest(name string, siteId string) *SpxPartitionCreateRequest {
	this := SpxPartitionCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewSpxPartitionCreateRequestWithDefaults instantiates a new SpxPartitionCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpxPartitionCreateRequestWithDefaults() *SpxPartitionCreateRequest {
	this := SpxPartitionCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SpxPartitionCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpxPartitionCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpxPartitionCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpxPartitionCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartitionCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SpxPartitionCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SpxPartitionCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SpxPartitionCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SpxPartitionCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value
func (o *SpxPartitionCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SpxPartitionCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SpxPartitionCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpxPartitionCreateRequest) GetVni() uint32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret uint32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartitionCreateRequest) GetVniOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *SpxPartitionCreateRequest) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableUint32 and assigns it to the Vni field.
func (o *SpxPartitionCreateRequest) SetVni(v uint32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *SpxPartitionCreateRequest) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *SpxPartitionCreateRequest) UnsetVni() {
	o.Vni.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpxPartitionCreateRequest) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartitionCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SpxPartitionCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SpxPartitionCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o SpxPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpxPartitionCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["siteId"] = o.SiteId
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *SpxPartitionCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpxPartitionCreateRequest := _SpxPartitionCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpxPartitionCreateRequest)

	if err != nil {
		return err
	}

	*o = SpxPartitionCreateRequest(varSpxPartitionCreateRequest)

	return err
}

type NullableSpxPartitionCreateRequest struct {
	value *SpxPartitionCreateRequest
	isSet bool
}

func (v NullableSpxPartitionCreateRequest) Get() *SpxPartitionCreateRequest {
	return v.value
}

func (v *NullableSpxPartitionCreateRequest) Set(val *SpxPartitionCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSpxPartitionCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSpxPartitionCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpxPartitionCreateRequest(val *SpxPartitionCreateRequest) *NullableSpxPartitionCreateRequest {
	return &NullableSpxPartitionCreateRequest{value: val, isSet: true}
}

func (v NullableSpxPartitionCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpxPartitionCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
