// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SpxPartition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpxPartition{}

// SpxPartition A tenant-owned Spectrum-X fabric partition. Core is the source of truth for its existence, identity, ownership, name, description, and VNI; labels are REST presentation metadata
type SpxPartition struct {
	// Unique ID shared by the REST projection and Core SPX Partition
	Id string `json:"id"`
	// Name of the SPX Partition
	Name string `json:"name"`
	// Optional description of the SPX Partition
	Description NullableString `json:"description"`
	// ID of the Site that owns the SPX Partition
	SiteId string `json:"siteId"`
	// Site summary when the Site relation is requested; otherwise null
	Site NullableSiteSummary `json:"site"`
	// ID of the Tenant that owns the SPX Partition
	TenantId string `json:"tenantId"`
	// Tenant summary when the Tenant relation is requested; otherwise null
	Tenant NullableTenantSummary `json:"tenant"`
	// Exact VNI accepted or allocated by Core
	Vni uint32 `json:"vni"`
	// REST presentation metadata retained independently of Core inventory. An SPX Partition without labels returns an empty object
	Labels map[string]string `json:"labels"`
	// Date and time the REST projection was created
	Created time.Time `json:"created"`
	// Date and time the REST projection was last reconciled or updated
	Updated time.Time `json:"updated"`
}

type _SpxPartition SpxPartition

// NewSpxPartition instantiates a new SpxPartition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpxPartition(id string, name string, description NullableString, siteId string, site NullableSiteSummary, tenantId string, tenant NullableTenantSummary, vni uint32, labels map[string]string, created time.Time, updated time.Time) *SpxPartition {
	this := SpxPartition{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.SiteId = siteId
	this.Site = site
	this.TenantId = tenantId
	this.Tenant = tenant
	this.Vni = vni
	this.Labels = labels
	this.Created = created
	this.Updated = updated
	return &this
}

// NewSpxPartitionWithDefaults instantiates a new SpxPartition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpxPartitionWithDefaults() *SpxPartition {
	this := SpxPartition{}
	return &this
}

// GetId returns the Id field value
func (o *SpxPartition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpxPartition) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SpxPartition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SpxPartition) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SpxPartition) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartition) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *SpxPartition) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetSiteId returns the SiteId field value
func (o *SpxPartition) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SpxPartition) SetSiteId(v string) {
	o.SiteId = v
}

// GetSite returns the Site field value
// If the value is explicit nil, the zero value for SiteSummary will be returned
func (o *SpxPartition) GetSite() SiteSummary {
	if o == nil || o.Site.Get() == nil {
		var ret SiteSummary
		return ret
	}

	return *o.Site.Get()
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartition) GetSiteOk() (*SiteSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Site.Get(), o.Site.IsSet()
}

// SetSite sets field value
func (o *SpxPartition) SetSite(v SiteSummary) {
	o.Site.Set(&v)
}

// GetTenantId returns the TenantId field value
func (o *SpxPartition) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *SpxPartition) SetTenantId(v string) {
	o.TenantId = v
}

// GetTenant returns the Tenant field value
// If the value is explicit nil, the zero value for TenantSummary will be returned
func (o *SpxPartition) GetTenant() TenantSummary {
	if o == nil || o.Tenant.Get() == nil {
		var ret TenantSummary
		return ret
	}

	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpxPartition) GetTenantOk() (*TenantSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// SetTenant sets field value
func (o *SpxPartition) SetTenant(v TenantSummary) {
	o.Tenant.Set(&v)
}

// GetVni returns the Vni field value
func (o *SpxPartition) GetVni() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Vni
}

// GetVniOk returns a tuple with the Vni field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetVniOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vni, true
}

// SetVni sets field value
func (o *SpxPartition) SetVni(v uint32) {
	o.Vni = v
}

// GetLabels returns the Labels field value
func (o *SpxPartition) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetLabelsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *SpxPartition) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value
func (o *SpxPartition) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *SpxPartition) SetCreated(v time.Time) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *SpxPartition) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *SpxPartition) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *SpxPartition) SetUpdated(v time.Time) {
	o.Updated = v
}

func (o SpxPartition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpxPartition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["siteId"] = o.SiteId
	toSerialize["site"] = o.Site.Get()
	toSerialize["tenantId"] = o.TenantId
	toSerialize["tenant"] = o.Tenant.Get()
	toSerialize["vni"] = o.Vni
	toSerialize["labels"] = o.Labels
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *SpxPartition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"siteId",
		"site",
		"tenantId",
		"tenant",
		"vni",
		"labels",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpxPartition := _SpxPartition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSpxPartition)

	if err != nil {
		return err
	}

	*o = SpxPartition(varSpxPartition)

	return err
}

type NullableSpxPartition struct {
	value *SpxPartition
	isSet bool
}

func (v NullableSpxPartition) Get() *SpxPartition {
	return v.value
}

func (v *NullableSpxPartition) Set(val *SpxPartition) {
	v.value = val
	v.isSet = true
}

func (v NullableSpxPartition) IsSet() bool {
	return v.isSet
}

func (v *NullableSpxPartition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpxPartition(val *SpxPartition) *NullableSpxPartition {
	return &NullableSpxPartition{value: val, isSet: true}
}

func (v NullableSpxPartition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpxPartition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
